// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAEL_V2.Data;

#nullable disable

namespace PAEL_V2.Migrations
{
    [DbContext(typeof(PAEL_V2Context))]
    partial class PAEL_V2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PAEL_V2.Models.Cours", b =>
                {
                    b.Property<int>("CoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoursId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FormationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CoursId");

                    b.HasIndex("FormationId");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("PAEL_V2.Models.Etudiant", b =>
                {
                    b.Property<int>("EtudiantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EtudiantId"));

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FormationId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EtudiantId");

                    b.HasIndex("FormationId");

                    b.ToTable("Etudiant");
                });

            modelBuilder.Entity("PAEL_V2.Models.Formation", b =>
                {
                    b.Property<int>("FormationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormationId"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FormationId");

                    b.ToTable("Formation");
                });

            modelBuilder.Entity("PAEL_V2.Models.Inscription", b =>
                {
                    b.Property<int>("InscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InscriptionId"));

                    b.Property<int?>("CoursId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("int");

                    b.Property<string>("EtudiantNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtudiantPrenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormationId")
                        .HasColumnType("int");

                    b.Property<string>("FormationNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InscriptionId");

                    b.HasIndex("CoursId");

                    b.HasIndex("EtudiantId");

                    b.HasIndex("FormationId");

                    b.ToTable("Inscription");
                });

            modelBuilder.Entity("PAEL_V2.Models.Cours", b =>
                {
                    b.HasOne("PAEL_V2.Models.Formation", null)
                        .WithMany("Cours")
                        .HasForeignKey("FormationId");
                });

            modelBuilder.Entity("PAEL_V2.Models.Etudiant", b =>
                {
                    b.HasOne("PAEL_V2.Models.Formation", null)
                        .WithMany("Etudiants")
                        .HasForeignKey("FormationId");
                });

            modelBuilder.Entity("PAEL_V2.Models.Inscription", b =>
                {
                    b.HasOne("PAEL_V2.Models.Cours", null)
                        .WithMany("Inscriptions")
                        .HasForeignKey("CoursId");

                    b.HasOne("PAEL_V2.Models.Etudiant", "Etudiant")
                        .WithMany("Inscriptions")
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAEL_V2.Models.Formation", "Formation")
                        .WithMany("Inscriptions")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etudiant");

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("PAEL_V2.Models.Cours", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("PAEL_V2.Models.Etudiant", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("PAEL_V2.Models.Formation", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("Etudiants");

                    b.Navigation("Inscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
